[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-vsphere"
  version = "v1.9.1"

  [constraint.metadata]
    govendor-exclude-prefixes = ["github.com/golang/protobuf","github.com/vmware/vic"]
    govendor-override = true

# NOTE: the following overrides were injected by govendor-override. It may be necessary to
# remove some of these overrides in order to produce a buildable vendor tree.
[[override]]
  name = "github.com/Sirupsen/logrus"
  revision = "89742aefa4b206dcf400792f3bd35b542998eb3b"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/agext/levenshtein"
  revision = "5f10fee965225ac1eecdc234c09daf5cd9e7f7b6"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "7e4b007599d4e2076d9a81be723b3912852dda2c"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-rundeck-api"
  revision = "f6af74d34d1ef69a511c59173876fc1174c11f0d"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/apparentlymart/go-textseg"
  revision = "b836f5c4d331d1945a2fead7188db25432d73b69"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/armon/go-radix"
  revision = "1fca145dffbcaa8fe914309b1ec0cfc67500fe61"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.8.34"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/bgentry/speakeasy"
  revision = "4aabc24848ce5fd31929f7d1e4ea74d3709c14cd"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/blang/semver"
  revision = "2ee87856327ba09384cabd113bc6b5d174e9ec0f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/davecgh/go-spew"
  revision = "346938d642f2ec3594ed81d874461961cd0faa76"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/dustinkirkland/golang-petname"
  revision = "d3c2ba80e75eeef10c5cf2fc76d2c809637376b3"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/fsouza/go-dockerclient"
  revision = "1d4f4ae73768d3ca16a6fb964694f58dc5eba601"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/go-ini/ini"
  revision = "766e555c68dc8bda90d197ee8946c37519c19409"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "3573b8b52aa7b37b9358d966a898feb387f62437"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-getter"
  revision = "a686900cb3753aa644dc4812be91ceaf9fdd3b98"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-hclog"
  revision = "b4e5765d1e5f00a0550911084f45f8214b5b83b9"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f09973e19c1dfcd120b2d9c4f168e68d6b5d5"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-plugin"
  revision = "a5174f84d7f8ff00fb07ab4ef1f380d32eee0e63"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-uuid"
  revision = "36289988d83ca270bc07c234c36f364b0dd9c9a7"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/go-version"
  revision = "e96d3840402619007766590ecea8dd7af1292276"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl"
  revision = "a4b07c25de5ff55ad3b8936cea69a79a3d95a855"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hcl2"
  revision = "44bad6dbf5490f5da17ec991e664df3d017b706f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/hil"
  revision = "fac2259da677551de1fb92b844c4d020a38d8468"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/logutils"
  revision = "0dc08b1671f34c4250ce212759ebd880f743d883"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/terraform"
  revision = "3505769600eec4a85a3be203a9c7eba7f97c5ade"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/hashicorp/yamux"
  revision = "d1caa6c97c9fc1cc9e83bbe34d0603f9ff0ce8bd"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mattn/go-isatty"
  revision = "fc9e8d8ef48496124e79ae0df75490096eccf6fe"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/cli"
  revision = "b633c78680fa6fb27ac81694f38c28f79602ebd9"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/copystructure"
  revision = "d23ffcb85de31694d6ccaa23ccb4a03e55c1303f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-testing-interface"
  revision = "9a441910b16872f7b8283682619b3761a9aa2222"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/hashstructure"
  revision = "6b17d669fac5e2f71c16658d781ec3fdd3802b69"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "53818660ed4955e899c0bcafa97299a388bd7c8e"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "63d60e9d0dbc60cf9164e6510889b0db6683d98c"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/pkg/errors"
  revision = "2b3a18b5f0fb6b4f9190549597d3f962c02bc5eb"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/posener/complete"
  revision = "f4461a52b6329c11190f11fe3384ec8aa964e21c"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/rancher/go-rancher"
  revision = "ec24b7f12fca9f78fbfcd62a0ea8bce14ade8792"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "b061729afc07e77a8aa4fad0a2fd840958f1942a"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/terraform-providers/terraform-provider-null"
  revision = "1e016b8a70416ce036b2600870723cc6f13e2e20"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/terraform-providers/terraform-provider-random"
  revision = "e6526ec8369cf8a96edee186f9e427dd9a9fb0b2"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/terraform-providers/terraform-provider-template"
  revision = "c28e0cec248a704ddbd5127bf47358609f1491aa"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/ulikunitz/xz"
  revision = "0c6b41e72360850ca4f98dc341fd999726ea007f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/vmware/govmomi"
  revision = "e3a01f9611c32b2362366434bcd671516e78955d"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "github.com/zclconf/go-cty"
  revision = "8bf222d6d03b7b336d013978f3acbfd877da428f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/crypto"
  revision = "7d9177d70076375b9a59c8fde23d52d9c4a7ecd5"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/net"
  revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/sys"
  revision = "b6e1ae21643682ce023deb8d152024597b0e9bb4"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "golang.org/x/text"
  revision = "e56139fd9c5bc7244c76116c68e500765bb6db6b"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "google.golang.org/genproto"
  revision = "ee236bd376b077c7a89f260c026c4735b195e459"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "google.golang.org/grpc"
  revision = "2308131c44e408bb7a4da392ed6849a0afe85b2f"
  [override.metadata]
    govendor-overridden=true

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.6.1"
  [override.metadata]
    govendor-overridden=true
