[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  branch = "master"
  name = "github.com/terraform-providers/terraform-provider-vsphere"
  [constraint.metadata]
    govendor-override = true
    govendor-exclude-prefixes = [
      "github.com/golang/protobuf",
      "github.com/vmware/vic",
    ]
